name: CI

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run eslint:check
      - run: npm run prettier:check
      - run: npm run stylelint:check
